sudo: false
language: ruby
rvm:
  - 1.8.7-p375
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
before_install:
- gem update --system
- gem install bundler -v ">= 1.15.3"
script: bin/rake
